export interface Creature {
  index: number;
  name: string;
  size: string;
  type: string;
  subtype?: string;
  alignment: string;
  armor_class?: number;
  hit_points: number;
  hit_dice?:string;
  speed?:string;
  strength?:number;
  dexterity?:number;
  constitution?:number;
  wisdom?:number;
  charisma?:number;
  intelligence?:number;
  constitution_save?:number;
  intelligence_save?:number;
  dexterity_save?:number;
  strength_save?:number;
  wisdom_save?:number;
  charisma_save?:number;
  challenge_rating:number;
  history?:number;
  perception?:number;
  religion?:number;
  medicine?:number;
  stealth?:number;
  persuasion?:number;
  insight?:number;
  deception?:number;
  arcana?:number;
  athletics?:number;
  acrobatics?:number;
  survival?:number;
  investigation?:number;
  nature?:number;
  performance?:number;
  intimidation?:number;
  reactions?:any[];
  damage_vulnerabilities?:string;
  damage_immunities?:string;
  damage_resistances?:string;
  condition_immunities?:string;
  languages?:string;
  senses?:string;
  lastLetter?:string;
  special_abilities?:any[];
  actions?:any[];
  legendary_actions?:any[];
  url?:string;
  instances?:any[];
  active?:boolean;
};
