export class Creature {
  index: number;
  name: string;
  size: string;
  type: string;
  subtype: string;
  alignment: string;
  armor_class: number;
  hit_points: number;
  hit_dice:string;
  speed:string;
  strength:number;
  dexterity:number;
  constitution:number;
  wisdom:number;
  charisma:number;
  intelligence:number;
  constitution_save:number;
  intelligence_save:number;
  strength_save:number;
  wisdom_save:number;
  charisma_save:number;
  challenge_rating:number;
  history:number;
  perception:number;
  religion:number;
  medicine:number;
  stealth:number;
  damage_vulnerabilities:string;
  damage_immunities:string;
  condition_immunities:string;
  languages:string;
  senses:string;
  lastLetter:string;
  special_abilities:any[];
  actions:any[];
  instances:any[];
  active:boolean;
};
